// Code generated by "stringer -type=Type"; DO NOT EDIT

package typ

import "fmt"

const _Type_name = "T無T炎T水T草T電T氷T闘T毒T地T飛T超T虫T岩T霊T竜T悪T鋼T妖"

var _Type_index = [...]uint8{0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
