// Code generated by "stringer -type=Effectiveness"; DO NOT EDIT

package fr

import "fmt"

const _Effectiveness_name = "Aucun_EffetPas_Très_EfficaceNormauxSuper_Efficace"

var _Effectiveness_index = [...]uint8{0, 11, 29, 36, 50}

func (i Effectiveness) String() string {
	if i < 0 || i >= Effectiveness(len(_Effectiveness_index)-1) {
		return fmt.Sprintf("Effectiveness(%d)", i)
	}
	return _Effectiveness_name[_Effectiveness_index[i]:_Effectiveness_index[i+1]]
}
