// Code generated by "stringer -type=Effectiveness"; DO NOT EDIT

package de

import "fmt"

const _Effectiveness_name = "Kein_EffektNicht_Sehr_EffektivNormalerSehr_Effektiv"

var _Effectiveness_index = [...]uint8{0, 11, 30, 38, 51}

func (i Effectiveness) String() string {
	if i < 0 || i >= Effectiveness(len(_Effectiveness_index)-1) {
		return fmt.Sprintf("Effectiveness(%d)", i)
	}
	return _Effectiveness_name[_Effectiveness_index[i]:_Effectiveness_index[i+1]]
}
