// Code generated by "stringer -type=Type"; DO NOT EDIT

package pokemon

import "fmt"

const _Type_name = "TypeNoneTypeNormalTypeFireTypeWaterTypeGrassTypeElectricTypeIceTypeFightingTypePoisonTypeGroundTypeFlyingTypePsychicTypeBugTypeRockTypeGhostTypeDragonTypeDarkTypeSteelTypeFairy"

var _Type_index = [...]uint8{0, 8, 18, 26, 35, 44, 56, 63, 75, 85, 95, 105, 116, 123, 131, 140, 150, 158, 167, 176}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
