// Code generated by "stringer -type=Effectiveness"; DO NOT EDIT

package es

import "fmt"

const _Effectiveness_name = "Sin_EfectoNo_Muy_EficazNormalSúper_Eficaz"

var _Effectiveness_index = [...]uint8{0, 10, 23, 29, 42}

func (i Effectiveness) String() string {
	if i < 0 || i >= Effectiveness(len(_Effectiveness_index)-1) {
		return fmt.Sprintf("Effectiveness(%d)", i)
	}
	return _Effectiveness_name[_Effectiveness_index[i]:_Effectiveness_index[i+1]]
}
