// Code generated by "stringer -type=Effectiveness"; DO NOT EDIT

package en

import "fmt"

const _Effectiveness_name = "No_EffectNot_Very_EffectiveNormalSuper_Effective"

var _Effectiveness_index = [...]uint8{0, 9, 27, 33, 48}

func (i Effectiveness) String() string {
	if i < 0 || i >= Effectiveness(len(_Effectiveness_index)-1) {
		return fmt.Sprintf("Effectiveness(%d)", i)
	}
	return _Effectiveness_name[_Effectiveness_index[i]:_Effectiveness_index[i+1]]
}
