// Code generated by "stringer -type=Type"; DO NOT EDIT

package en

import "fmt"

const _Type_name = "NormalFireWaterGrassElectricIceFightingPoisonGroundFlyingPsychicBugRockGhostDragonDarkSteelFairy"

var _Type_index = [...]uint8{0, 6, 10, 15, 20, 28, 31, 39, 45, 51, 57, 64, 67, 71, 76, 82, 86, 91, 96}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
