// Code generated by "stringer -type=Pokemon"; DO NOT EDIT

package fr

import "fmt"

const _Pokemon_name = "BulbizarreHerbizarreFlorizarreSalamècheReptincelDracaufeuCarapuceCarabaffeTortankChenipanChrysacierPapilusionAspicotCoconfortDardargnanRoucoolRoucoupsRoucarnageRattataRattatacPiafabecRapasdepicAboArbokPikachuRaichuSabeletteSablaireauNidoran_female_NidorinaNidoqueenNidoran_male_NidorinoNidokingMéloféeMélodelfeGoupixFeunardRondoudouGrodoudouNosferaptiNosferaltoMystherbeOrtideRafflesiaParasParasectMimitossAéromiteTaupiqueurTriopikeurMiaoussPersianPsykokwakAkwakwakFérosingeColossingeCaninosArcaninPtitardTêtarteTartardAbraKadabraAlakazamMachocMachopeurMackogneurChétiflorBoustiflorEmpiflorTentacoolTentacruelRacaillouGravalanchGrolemPonytaGalopaRamolossFlagadossMagnétiMagnétonCanartichoDoduoDodrioOtariaLamantineTadmorvGrotadmorvKokiyasCrustabriFantominusSpectrumEctoplasmaOnixSoporifikHypnomadeKrabbyKrabbossVoltorbeÉlectrodeNoeunoeufNoadkokoOsselaitOssatueurKickleeTygnonExcelangueSmogoSmogogoRhinocorneRhinoférosLeveinardSaquedeneuKangourexHypotrempeHypocéanPoissirènePoissoroyStariStarossM_full_stop__space_MimeInsécateurLippoutouÉlektekMagmarScarabruteTaurosMagicarpeLéviatorLokhlassMétamorphÉvoliAqualiVoltaliPyroliPorygonAmonitaAmonistarKabutoKabutopsPtéraRonflexArtikodinÉlecthorSulfuraMinidracoDracoDracolosseMewtwoMew"

var _Pokemon_index = [...]uint16{0, 10, 20, 30, 40, 49, 58, 66, 75, 82, 90, 100, 110, 117, 126, 136, 143, 151, 161, 168, 176, 184, 194, 197, 202, 209, 215, 224, 234, 249, 257, 266, 279, 287, 295, 304, 314, 320, 327, 336, 345, 355, 365, 374, 380, 389, 394, 402, 410, 419, 429, 439, 446, 453, 462, 470, 480, 490, 497, 504, 511, 519, 526, 530, 537, 545, 551, 560, 570, 580, 590, 598, 607, 617, 626, 636, 642, 648, 654, 662, 671, 679, 688, 698, 703, 709, 715, 724, 731, 741, 748, 757, 767, 775, 785, 789, 798, 807, 813, 821, 829, 839, 848, 856, 864, 873, 880, 886, 896, 901, 908, 918, 929, 938, 948, 957, 967, 976, 987, 996, 1001, 1008, 1031, 1042, 1051, 1059, 1065, 1075, 1081, 1090, 1099, 1107, 1117, 1123, 1129, 1136, 1142, 1149, 1156, 1165, 1171, 1179, 1185, 1192, 1201, 1210, 1217, 1226, 1231, 1241, 1247, 1250}

func (i Pokemon) String() string {
	i -= 1
	if i < 0 || i >= Pokemon(len(_Pokemon_index)-1) {
		return fmt.Sprintf("Pokemon(%d)", i+1)
	}
	return _Pokemon_name[_Pokemon_index[i]:_Pokemon_index[i+1]]
}
