// Code generated by "stringer -type=Type"; DO NOT EDIT

package fr

import "fmt"

const _Type_name = "AucunNormalFeuEauPlanteÉlectriqueGlaceCombatPoisonSolVolPsyInsecteRocheSpectreDragonTénèbresAcierFée"

var _Type_index = [...]uint8{0, 5, 11, 14, 17, 23, 34, 39, 45, 51, 54, 57, 60, 67, 72, 79, 85, 95, 100, 104}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
