// Code generated by "stringer -type=Type"; DO NOT EDIT

package fr

import "fmt"

const _Type_name = "NormalFeuEauPlanteÉlectriqueGlaceCombatPoisonSolVolPsyInsecteRocheSpectreDragonTénèbresAcierFée"

var _Type_index = [...]uint8{0, 6, 9, 12, 18, 29, 34, 40, 46, 49, 52, 55, 62, 67, 74, 80, 90, 95, 99}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
