// Code generated by "stringer -type=Type"; DO NOT EDIT

package es

import "fmt"

const _Type_name = "NormalFuegoAguaPlantaEléctricoHieloLuchaVenenoTierraVoladorPsíquicoInsectoRocaFantasmaDragónSiniestroAceroHada"

var _Type_index = [...]uint8{0, 6, 11, 15, 21, 31, 36, 41, 47, 53, 60, 69, 76, 80, 88, 95, 104, 109, 113}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
