// Code generated by "stringer -type=Effectiveness"; DO NOT EDIT

package ko

import "fmt"

const _Effectiveness_name = "효과가없다별로인표준굉장한"

var _Effectiveness_index = [...]uint8{0, 15, 24, 30, 39}

func (i Effectiveness) String() string {
	if i < 0 || i >= Effectiveness(len(_Effectiveness_index)-1) {
		return fmt.Sprintf("Effectiveness(%d)", i)
	}
	return _Effectiveness_name[_Effectiveness_index[i]:_Effectiveness_index[i+1]]
}
