// Code generated by "stringer -type=Type"; DO NOT EDIT

package es

import "fmt"

const _Type_name = "NingunaNormalFuegoAguaPlantaEléctricoHieloLuchaVenenoTierraVoladorPsíquicoInsectoRocaFantasmaDragónSiniestroAceroHada"

var _Type_index = [...]uint8{0, 7, 13, 18, 22, 28, 38, 43, 48, 54, 60, 67, 76, 83, 87, 95, 102, 111, 116, 120}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
