// Code generated by "stringer -type=Effectiveness"; DO NOT EDIT

package it

import "fmt"

const _Effectiveness_name = "Nessun_EffettoNon_Molto_EfficaceNormaleSuper_Efficace"

var _Effectiveness_index = [...]uint8{0, 14, 32, 39, 53}

func (i Effectiveness) String() string {
	if i < 0 || i >= Effectiveness(len(_Effectiveness_index)-1) {
		return fmt.Sprintf("Effectiveness(%d)", i)
	}
	return _Effectiveness_name[_Effectiveness_index[i]:_Effectiveness_index[i+1]]
}
