// Code generated by "stringer -type=Type"; DO NOT EDIT

package it

import "fmt"

const _Type_name = "NessunaNormaleFuocoAcquaErbaElettroGhiaccioLottaVelenoTerraVolantePsicoColeott_full_stop_RocciaSpettroDragoBuioAcciaioFolletto"

var _Type_index = [...]uint8{0, 7, 14, 19, 24, 28, 35, 43, 48, 54, 59, 66, 71, 89, 95, 102, 107, 111, 118, 126}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
