// Code generated by "stringer -type=Pokemon"; DO NOT EDIT

package it

import "fmt"

const _Pokemon_name = "BulbasaurIvysaurVenusaurCharmanderCharmeleonCharizardSquirtleWartortleBlastoiseCaterpieMetapodButterfreeWeedleKakunaBeedrillPidgeyPidgeottoPidgeotRattataRaticateSpearowFearowEkansArbokPikachuRaichuSandshrewSandslashNidoran_female_NidorinaNidoqueenNidoran_male_NidorinoNidokingClefairyClefableVulpixNinetalesJigglypuffWigglytuffZubatGolbatOddishGloomVileplumeParasParasectVenonatVenomothDiglettDugtrioMeowthPersianPsyduckGolduckMankeyPrimeapeGrowlitheArcaninePoliwagPoliwhirlPoliwrathAbraKadabraAlakazamMachopMachokeMachampBellsproutWeepinbellVictreebelTentacoolTentacruelGeodudeGravelerGolemPonytaRapidashSlowpokeSlowbroMagnemiteMagnetonFarfetch_apostrophe_dDoduoDodrioSeelDewgongGrimerMukShellderCloysterGastlyHaunterGengarOnixDrowzeeHypnoKrabbyKinglerVoltorbElectrodeExeggcuteExeggutorCuboneMarowakHitmonleeHitmonchanLickitungKoffingWeezingRhyhornRhydonChanseyTangelaKangaskhanHorseaSeadraGoldeenSeakingStaryuStarmieMr_full_stop__space_MimeScytherJynxElectabuzzMagmarPinsirTaurosMagikarpGyaradosLaprasDittoEeveeVaporeonJolteonFlareonPorygonOmanyteOmastarKabutoKabutopsAerodactylSnorlaxArticunoZapdosMoltresDratiniDragonairDragoniteMewtwoMew"

var _Pokemon_index = [...]uint16{0, 9, 16, 24, 34, 44, 53, 61, 70, 79, 87, 94, 104, 110, 116, 124, 130, 139, 146, 153, 161, 168, 174, 179, 184, 191, 197, 206, 215, 230, 238, 247, 260, 268, 276, 284, 292, 298, 307, 317, 327, 332, 338, 344, 349, 358, 363, 371, 378, 386, 393, 400, 406, 413, 420, 427, 433, 441, 450, 458, 465, 474, 483, 487, 494, 502, 508, 515, 522, 532, 542, 552, 561, 571, 578, 586, 591, 597, 605, 613, 620, 629, 637, 658, 663, 669, 673, 680, 686, 689, 697, 705, 711, 718, 724, 728, 735, 740, 746, 753, 760, 769, 778, 787, 793, 800, 809, 819, 828, 835, 842, 849, 855, 862, 869, 879, 885, 891, 898, 905, 911, 918, 942, 949, 953, 963, 969, 975, 981, 989, 997, 1003, 1008, 1013, 1021, 1028, 1035, 1042, 1049, 1056, 1062, 1070, 1080, 1087, 1095, 1101, 1108, 1115, 1124, 1133, 1139, 1142}

func (i Pokemon) String() string {
	i -= 1
	if i < 0 || i >= Pokemon(len(_Pokemon_index)-1) {
		return fmt.Sprintf("Pokemon(%d)", i+1)
	}
	return _Pokemon_name[_Pokemon_index[i]:_Pokemon_index[i+1]]
}
