// Code generated by "stringer -type=Type"; DO NOT EDIT

package zhCHT

import "fmt"

const _Type_name = "沒有一般炎水草電冰格鬥毒地上飛行超能力蟲岩石幽靈龍惡鋼鐵妖精"

var _Type_index = [...]uint8{0, 6, 12, 15, 18, 21, 24, 27, 33, 36, 42, 48, 57, 60, 66, 72, 75, 78, 84, 90}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
