package pokemon

import (
	m "github.com/asukakenji/pokemon-go/move"
)

var moves = [][]m.Move{
	nil,
	{m.Tackle, m.VineWhip, m.SeedBomb, m.SludgeBomb, m.PowerWhip},                       // 001: Bulbasaur (フシギダネ)
	{m.RazorLeaf, m.VineWhip, m.SolarBeam, m.SludgeBomb, m.PowerWhip},                   // 002: Ivysaur (フシギソウ)
	{m.RazorLeaf, m.VineWhip, m.SolarBeam, m.SludgeBomb, m.PetalBlizzard},               // 003: Venusaur (フシギバナ)
	{m.Ember, m.Scratch, m.FlameBurst, m.Flamethrower, m.FlameCharge},                   // 004: Charmander (ヒトカゲ)
	{m.Ember, m.Scratch, m.FlameBurst, m.Flamethrower, m.FirePunch},                     // 005: Charmeleon (リザード)
	{m.Ember, m.WingAttack, m.DragonClaw, m.Flamethrower, m.FireBlast},                  // 006: Charizard (リザードン)
	{m.Bubble, m.Tackle, m.AquaJet, m.AquaTail, m.WaterPulse},                           // 007: Squirtle (ゼニガメ)
	{m.Bite, m.WaterGun, m.AquaJet, m.HydroPump, m.IceBeam},                             // 008: Wartortle (カメール)
	{m.Bite, m.WaterGun, m.IceBeam, m.HydroPump, m.FlashCannon},                         // 009: Blastoise (カメックス)
	{m.BugBite, m.Tackle, m.Struggle},                                                   // 010: Caterpie (キャタピー)
	{m.BugBite, m.Tackle, m.Struggle},                                                   // 011: Metapod (トランセル)
	{m.BugBite, m.Confusion, m.Psychic, m.BugBuzz, m.SignalBeam},                        // 012: Butterfree (バタフリー)
	{m.BugBite, m.PoisonSting, m.Struggle},                                              // 013: Weedle (ビードル)
	{m.BugBite, m.PoisonJab, m.Struggle},                                                // 014: Kakuna (コクーン)
	{m.BugBite, m.PoisonJab, m.AerialAce, m.SludgeBomb, m.X_Scissor},                    // 015: Beedrill (スピアー)
	{m.Tackle, m.QuickAttack, m.Twister, m.AerialAce, m.AirCutter},                      // 016: Pidgey (ポッポ)
	{m.SteelWing, m.WingAttack, m.Twister, m.AerialAce, m.AirCutter},                    // 017: Pidgeotto (ピジョン)
	{m.SteelWing, m.WingAttack, m.Hurricane, m.AerialAce, m.AirCutter},                  // 018: Pidgeot (ピジョット)
	{m.Tackle, m.QuickAttack, m.Dig, m.HyperFang, m.BodySlam},                           // 019: Rattata (コラッタ)
	{m.Bite, m.QuickAttack, m.Dig, m.HyperFang, m.HyperBeam},                            // 020: Raticate (ラッタ)
	{m.Peck, m.QuickAttack, m.AerialAce, m.Twister, m.DrillPeck},                        // 021: Spearow (オニスズメ)
	{m.Peck, m.SteelWing, m.AerialAce, m.Twister, m.DrillRun},                           // 022: Fearow (オニドリル)
	{m.Acid, m.PoisonSting, m.GunkShot, m.SludgeBomb, m.Wrap},                           // 023: Ekans (アーボ)
	{m.Acid, m.Bite, m.GunkShot, m.SludgeWave, m.DarkPulse},                             // 024: Arbok (アーボック)
	{m.QuickAttack, m.ThunderShock, m.Thunderbolt, m.Discharge, m.Thunder},              // 025: Pikachu (ピカチュウ)
	{m.Spark, m.ThunderShock, m.BrickBreak, m.ThunderPunch, m.Thunder},                  // 026: Raichu (ライチュウ)
	{m.Scratch, m.MudShot, m.Dig, m.RockSlide, m.RockTomb},                              // 027: Sandshrew (サンド)
	{m.MetalClaw, m.MudShot, m.RockTomb, m.Bulldoze, m.Earthquake},                      // 028: Sandslash (サンドパン)
	{m.PoisonSting, m.Bite, m.PoisonFang, m.SludgeBomb, m.BodySlam},                     // 029: Nidoran♀ (ニドラン♀)
	{m.PoisonSting, m.Bite, m.PoisonFang, m.SludgeBomb, m.Dig},                          // 030: Nidorina (ニドリーナ)
	{m.PoisonJab, m.Bite, m.StoneEdge, m.SludgeWave, m.Earthquake},                      // 031: Nidoqueen (ニドクイン)
	{m.PoisonSting, m.Peck, m.HornAttack, m.BodySlam, m.SludgeBomb},                     // 032: Nidoran♂ (ニドラン♂)
	{m.PoisonJab, m.Bite, m.HornAttack, m.Dig, m.SludgeBomb},                            // 033: Nidorino (ニドリーノ)
	{m.PoisonJab, m.FuryCutter, m.Megahorn, m.Earthquake, m.SludgeWave},                 // 034: Nidoking (ニドキング)
	{m.ZenHeadbutt, m.Pound, m.BodySlam, m.DisarmingVoice, m.Moonblast},                 // 035: Clefairy (ピッピ)
	{m.ZenHeadbutt, m.Pound, m.Psychic, m.DazzlingGleam, m.Moonblast},                   // 036: Clefable (ピクシー)
	{m.QuickAttack, m.Ember, m.Flamethrower, m.BodySlam, m.FlameCharge},                 // 037: Vulpix (ロコン)
	{m.FeintAttack, m.Ember, m.HeatWave, m.FireBlast, m.Flamethrower},                   // 038: Ninetales (キュウコン)
	{m.FeintAttack, m.Pound, m.DisarmingVoice, m.BodySlam, m.PlayRough},                 // 039: Jigglypuff (プリン)
	{m.FeintAttack, m.Pound, m.DazzlingGleam, m.HyperBeam, m.PlayRough},                 // 040: Wigglytuff (プクリン)
	{m.Bite, m.QuickAttack, m.SludgeBomb, m.PoisonFang, m.AirCutter},                    // 041: Zubat (ズバット)
	{m.Bite, m.WingAttack, m.OminousWind, m.PoisonFang, m.AirCutter},                    // 042: Golbat (ゴルバット)
	{m.RazorLeaf, m.Acid, m.Moonblast, m.SeedBomb, m.SludgeBomb},                        // 043: Oddish (ナゾノクサ)
	{m.RazorLeaf, m.Acid, m.Moonblast, m.PetalBlizzard, m.SludgeBomb},                   // 044: Gloom (クサイハナ)
	{m.RazorLeaf, m.Acid, m.Moonblast, m.PetalBlizzard, m.SolarBeam},                    // 045: Vileplume (ラフレシア)
	{m.BugBite, m.Scratch, m.SeedBomb, m.X_Scissor, m.CrossPoison},                      // 046: Paras (パラス)
	{m.BugBite, m.FuryCutter, m.SolarBeam, m.X_Scissor, m.CrossPoison},                  // 047: Parasect (パラセクト)
	{m.Confusion, m.BugBite, m.SignalBeam, m.PoisonFang, m.Psybeam},                     // 048: Venonat (コンパン)
	{m.Confusion, m.BugBite, m.BugBuzz, m.PoisonFang, m.Psychic},                        // 049: Venomoth (モルフォン)
	{m.Scratch, m.MudShot, m.RockTomb, m.Dig, m.MudBomb},                                // 050: Diglett (ディグダ)
	{m.SuckerPunch, m.MudShot, m.StoneEdge, m.Earthquake, m.MudBomb},                    // 051: Dugtrio (ダグトリオ)
	{m.Scratch, m.Bite, m.DarkPulse, m.NightSlash, m.BodySlam},                          // 052: Meowth (ニャース)
	{m.Scratch, m.FeintAttack, m.PlayRough, m.PowerGem, m.NightSlash},                   // 053: Persian (ペルシアン)
	{m.ZenHeadbutt, m.WaterGun, m.AquaTail, m.CrossChop, m.Psybeam},                     // 054: Psyduck (コダック)
	{m.Confusion, m.WaterGun, m.HydroPump, m.IceBeam, m.Psychic},                        // 055: Golduck (ゴルダック)
	{m.KarateChop, m.Scratch, m.BrickBreak, m.CrossChop, m.LowSweep},                    // 056: Mankey (マンキー)
	{m.KarateChop, m.LowKick, m.NightSlash, m.CrossChop, m.LowSweep},                    // 057: Primeape (オコリザル)
	{m.Ember, m.Bite, m.FlameWheel, m.BodySlam, m.Flamethrower},                         // 058: Growlithe (ガーディ)
	{m.FireFang, m.Bite, m.FireBlast, m.Bulldoze, m.Flamethrower},                       // 059: Arcanine (ウインディ)
	{m.Bubble, m.MudShot, m.BodySlam, m.BubbleBeam, m.MudBomb},                          // 060: Poliwag (ニョロモ)
	{m.Bubble, m.MudShot, m.Scald, m.BubbleBeam, m.MudBomb},                             // 061: Poliwhirl (ニョロゾ)
	{m.Bubble, m.MudShot, m.IcePunch, m.HydroPump, m.Submission},                        // 062: Poliwrath (ニョロボン)
	{m.ZenHeadbutt, m.ShadowBall, m.SignalBeam, m.Psyshock},                             // 063: Abra (ケーシィ)
	{m.Confusion, m.PsychoCut, m.ShadowBall, m.DazzlingGleam, m.Psybeam},                // 064: Kadabra (ユンゲラー)
	{m.Confusion, m.PsychoCut, m.ShadowBall, m.DazzlingGleam, m.Psychic},                // 065: Alakazam (フーディン)
	{m.LowKick, m.KarateChop, m.BrickBreak, m.CrossChop, m.LowSweep},                    // 066: Machop (ワンリキー)
	{m.LowKick, m.KarateChop, m.BrickBreak, m.CrossChop, m.Submission},                  // 067: Machoke (ゴーリキー)
	{m.BulletPunch, m.KarateChop, m.StoneEdge, m.CrossChop, m.Submission},               // 068: Machamp (カイリキー)
	{m.Acid, m.VineWhip, m.SludgeBomb, m.PowerWhip, m.Wrap},                             // 069: Bellsprout (マダツボミ)
	{m.Acid, m.RazorLeaf, m.SludgeBomb, m.PowerWhip, m.SeedBomb},                        // 070: Weepinbell (ウツドン)
	{m.Acid, m.RazorLeaf, m.SludgeBomb, m.LeafBlade, m.SolarBeam},                       // 071: Victreebel (ウツボット)
	{m.Bubble, m.PoisonSting, m.BubbleBeam, m.WaterPulse, m.Wrap},                       // 072: Tentacool (メノクラゲ)
	{m.Acid, m.PoisonJab, m.Blizzard, m.HydroPump, m.SludgeWave},                        // 073: Tentacruel (ドククラゲ)
	{m.RockThrow, m.Tackle, m.RockSlide, m.Dig, m.RockTomb},                             // 074: Geodude (イシツブテ)
	{m.RockThrow, m.MudShot, m.RockSlide, m.Dig, m.StoneEdge},                           // 075: Graveler (ゴローン)
	{m.RockThrow, m.MudShot, m.AncientPower, m.Earthquake, m.StoneEdge},                 // 076: Golem (ゴローニャ)
	{m.Tackle, m.Ember, m.FlameWheel, m.FireBlast, m.FlameCharge},                       // 077: Ponyta (ポニータ)
	{m.LowKick, m.Ember, m.HeatWave, m.FireBlast, m.DrillRun},                           // 078: Rapidash (ギャロップ)
	{m.WaterGun, m.Confusion, m.Psychic, m.WaterPulse, m.Psyshock},                      // 079: Slowpoke (ヤドン)
	{m.WaterGun, m.Confusion, m.Psychic, m.WaterPulse, m.IceBeam},                       // 080: Slowbro (ヤドラン)
	{m.Spark, m.ThunderShock, m.MagnetBomb, m.Discharge, m.Thunderbolt},                 // 081: Magnemite (コイル)
	{m.Spark, m.ThunderShock, m.MagnetBomb, m.Discharge, m.FlashCannon},                 // 082: Magneton (レアコイル)
	{m.FuryCutter, m.AirCutter},                                                         // 083: Farfetch'd (カモネギ)
	{m.Peck, m.QuickAttack, m.Swift, m.AerialAce, m.DrillPeck},                          // 084: Doduo (ドードー)
	{m.SteelWing, m.FeintAttack, m.DrillPeck, m.AerialAce, m.AirCutter},                 // 085: Dodrio (ドードリオ)
	{m.WaterGun, m.IceShard, m.AquaJet, m.IcyWind, m.AquaTail},                          // 086: Seel (パウワウ)
	{m.FrostBreath, m.IceShard, m.AquaJet, m.IcyWind, m.Blizzard},                       // 087: Dewgong (ジュゴン)
	{m.MudSlap, m.Acid, m.Sludge, m.SludgeBomb, m.MudBomb},                              // 088: Grimer (ベトベター)
	{m.PoisonJab, m.Acid, m.SludgeWave, m.SludgeBomb, m.DarkPulse},                      // 089: Muk (ベトベトン)
	{m.IceShard, m.Tackle, m.IcyWind, m.WaterPulse, m.BubbleBeam},                       // 090: Shellder (シェルダー)
	{m.IceShard, m.FrostBreath, m.IcyWind, m.Blizzard, m.HydroPump},                     // 091: Cloyster (パルシェン)
	{m.Lick, m.SuckerPunch, m.DarkPulse, m.SludgeBomb, m.OminousWind},                   // 092: Gastly (ゴース)
	{m.Lick, m.ShadowClaw, m.DarkPulse, m.SludgeBomb, m.ShadowBall},                     // 093: Haunter (ゴースト)
	{m.ShadowClaw, m.SuckerPunch, m.DarkPulse, m.SludgeWave, m.ShadowBall},              // 094: Gengar (ゲンガー)
	{m.RockThrow, m.Tackle, m.RockSlide, m.StoneEdge, m.IronHead},                       // 095: Onix (イワーク)
	{m.Pound, m.Confusion, m.Psychic, m.Psyshock, m.Psybeam},                            // 096: Drowzee (スリープ)
	{m.ZenHeadbutt, m.Confusion, m.Psychic, m.Psyshock, m.ShadowBall},                   // 097: Hypno (スリーパー)
	{m.Bubble, m.MudShot, m.ViceGrip, m.WaterPulse, m.BubbleBeam},                       // 098: Krabby (クラブ)
	{m.MetalClaw, m.MudShot, m.ViceGrip, m.WaterPulse, m.X_Scissor},                     // 099: Kingler (キングラー)
	{m.Tackle, m.Spark, m.Thunderbolt, m.Discharge, m.SignalBeam},                       // 100: Voltorb (ビリリダマ)
	{m.Tackle, m.Spark, m.Thunderbolt, m.Discharge, m.HyperBeam},                        // 101: Electrode (マルマイン)
	{m.Confusion, m.Psychic, m.SeedBomb, m.AncientPower},                                // 102: Exeggcute (タマタマ)
	{m.Confusion, m.ZenHeadbutt, m.Psychic, m.SeedBomb, m.SolarBeam},                    // 103: Exeggutor (ナッシー)
	{m.RockSmash, m.MudSlap, m.BoneClub, m.Dig, m.Bulldoze},                             // 104: Cubone (カラカラ)
	{m.RockSmash, m.MudSlap, m.BoneClub, m.Dig, m.Earthquake},                           // 105: Marowak (ガラガラ)
	{m.LowKick, m.RockSmash, m.LowSweep, m.StoneEdge, m.Stomp},                          // 106: Hitmonlee (サワムラー)
	{m.BulletPunch, m.RockSmash, m.FirePunch, m.IcePunch, m.ThunderPunch, m.BrickBreak}, // 107: Hitmonchan (エビワラー)
	{m.Lick, m.ZenHeadbutt, m.HyperBeam, m.Stomp, m.PowerWhip},                          // 108: Lickitung (ベロリンガ)
	{m.Tackle, m.Acid, m.DarkPulse, m.Sludge, m.SludgeBomb},                             // 109: Koffing (ドガース)
	{m.Tackle, m.Acid, m.DarkPulse, m.ShadowBall, m.SludgeBomb},                         // 110: Weezing (マタドガス)
	{m.RockSmash, m.MudSlap, m.Bulldoze, m.Stomp, m.HornAttack},                         // 111: Rhyhorn (サイホーン)
	{m.RockSmash, m.MudSlap, m.Earthquake, m.StoneEdge, m.Megahorn},                     // 112: Rhydon (サイドン)
	{m.Pound, m.ZenHeadbutt, m.DazzlingGleam, m.Psybeam, m.Psychic},                     // 113: Chansey (ラッキー)
	{m.VineWhip, m.SludgeBomb, m.SolarBeam, m.PowerWhip},                                // 114: Tangela (モンジャラ)
	{m.LowKick, m.MudSlap, m.Earthquake, m.BrickBreak, m.Stomp},                         // 115: Kangaskhan (ガルーラ)
	{m.WaterGun, m.Bubble, m.BubbleBeam, m.DragonPulse, m.FlashCannon},                  // 116: Horsea (タッツー)
	{m.WaterGun, m.DragonBreath, m.HydroPump, m.DragonPulse, m.Blizzard},                // 117: Seadra (シードラ)
	{m.MudShot, m.Peck, m.AquaTail, m.HornAttack, m.WaterPulse},                         // 118: Goldeen (トサキント)
	{m.PoisonJab, m.Peck, m.DrillRun, m.Megahorn, m.IcyWind},                            // 119: Seaking (アズマオウ)
	{m.WaterGun, m.QuickAttack, m.BubbleBeam, m.PowerGem, m.Swift},                      // 120: Staryu (ヒトデマン)
	{m.WaterGun, m.QuickAttack, m.HydroPump, m.PowerGem, m.Psybeam},                     // 121: Starmie (スターミー)
	{m.Confusion, m.ZenHeadbutt, m.ShadowBall, m.Psybeam, m.Psychic},                    // 122: Mr. Mime (バリヤード)
	{m.SteelWing, m.FuryCutter, m.BugBuzz, m.X_Scissor, m.NightSlash},                   // 123: Scyther (ストライク)
	{m.Pound, m.FrostBreath, m.Psyshock, m.IcePunch, m.DrainingKiss},                    // 124: Jynx (ルージュラ)
	{m.LowKick, m.ThunderShock, m.Thunderbolt, m.Thunder, m.ThunderPunch},               // 125: Electabuzz (エレブー)
	{m.KarateChop, m.Ember, m.FireBlast, m.Flamethrower, m.FirePunch},                   // 126: Magmar (ブーバー)
	{m.FuryCutter, m.RockSmash, m.Submission, m.ViceGrip, m.X_Scissor},                  // 127: Pinsir (カイロス)
	{m.Tackle, m.ZenHeadbutt, m.Earthquake, m.IronHead, m.HornAttack},                   // 128: Tauros (ケンタロス)
	{m.Splash, m.Struggle},                                                              // 129: Magikarp (コイキング)
	{m.Bite, m.DragonBreath, m.Twister, m.HydroPump, m.DragonPulse},                     // 130: Gyarados (ギャラドス)
	{m.FrostBreath, m.IceShard, m.IceBeam, m.DragonPulse, m.Blizzard},                   // 131: Lapras (ラプラス)
	nil, // 132: Ditto (メタモン)
	{m.Tackle, m.QuickAttack, m.BodySlam, m.Dig, m.Swift},               // 133: Eevee (イーブイ)
	{m.WaterGun, m.AquaTail, m.WaterPulse, m.HydroPump},                 // 134: Vaporeon (シャワーズ)
	{m.ThunderShock, m.Thunderbolt, m.Discharge, m.Thunder},             // 135: Jolteon (サンダース)
	{m.Ember, m.Flamethrower, m.FireBlast, m.HeatWave},                  // 136: Flareon (ブースター)
	{m.Tackle, m.QuickAttack, m.Discharge, m.Psybeam, m.SignalBeam},     // 137: Porygon (ポリゴン)
	{m.WaterGun, m.MudShot, m.RockTomb, m.AncientPower, m.Brine},        // 138: Omanyte (オムナイト)
	{m.WaterGun, m.RockThrow, m.RockSlide, m.AncientPower, m.HydroPump}, // 139: Omastar (オムスター)
	{m.Scratch, m.MudShot, m.AquaJet, m.RockTomb, m.AncientPower},       // 140: Kabuto (カブト)
	{m.FuryCutter, m.MudShot, m.WaterPulse, m.AncientPower},             // 141: Kabutops (カブトプス)
	{m.Bite, m.SteelWing, m.IronHead, m.HyperBeam, m.AncientPower},      // 142: Aerodactyl (プテラ)
	{m.Lick, m.ZenHeadbutt, m.HyperBeam, m.Earthquake, m.BodySlam},      // 143: Snorlax (カビゴン)
	nil, // 144: Articuno (フリーザー)
	nil, // 145: Zapdos (サンダー)
	nil, // 146: Moltres (ファイヤー)
	{m.DragonBreath, m.Wrap, m.AquaTail, m.Twister},                         // 147: Dratini (ミニリュウ)
	{m.DragonBreath, m.Wrap, m.AquaTail, m.DragonPulse},                     // 148: Dragonair (ハクリュー)
	{m.DragonBreath, m.SteelWing, m.HyperBeam, m.DragonClaw, m.DragonPulse}, // 149: Dragonite (カイリュー)
	nil, // 150: Mewtwo (ミュウツー)
	nil, // 151: Mew (ミュウ)
}
