// Code generated by "stringer -type=Type"; DO NOT EDIT

package de

import "fmt"

const _Type_name = "NormalFeuerWasserPflanzeElektroEisKampfGiftBodenFlugPsychoKäferGesteinGeistDracheUnlichtStahlFee"

var _Type_index = [...]uint8{0, 6, 11, 17, 24, 31, 34, 39, 43, 48, 52, 58, 64, 71, 76, 82, 89, 94, 97}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
