// Code generated by "stringer -type=Type"; DO NOT EDIT

package ja

import "fmt"

const _Type_name = "なしノーマルほのおみずくさでんきこおりかくとうどくじめんひこうエスパーむしいわゴーストドラゴンあくはがねフェアリー"

var _Type_index = [...]uint8{0, 6, 18, 27, 33, 39, 48, 57, 69, 75, 84, 93, 105, 111, 117, 129, 141, 147, 156, 171}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
