// Code generated by "stringer -type=Type"; DO NOT EDIT

package it

import "fmt"

const _Type_name = "NormaleFuocoAcquaErbaElettroGhiaccioLottaVelenoTerraVolantePsicoColeotteroRocciaSpettroDragoBuioAcciaioFolletto"

var _Type_index = [...]uint8{0, 7, 12, 17, 21, 28, 36, 41, 47, 52, 59, 64, 74, 80, 87, 92, 96, 103, 111}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
