// Code generated by "stringer -type=StandardMove"; DO NOT EDIT

package move

import "fmt"

const _StandardMove_name = "AcidBiteBubbleBugBiteBulletPunchConfusionCutDragonBreathEmberFeintAttackFireFangFrostBreathFuryCutterIceShardKarateChopLickLowKickMetalClawMudShotMudSlapPeckPoisonJabPoisonStingPoundPsychoCutQuickAttackRazorLeafRockSmashRockThrowScratchShadowClawSparkSplashSteelWingSuckerPunchTackleThunderShockVineWhipWaterGunWingAttackZenHeadbutt"

var _StandardMove_index = [...]uint16{0, 4, 8, 14, 21, 32, 41, 44, 56, 61, 72, 80, 91, 101, 109, 119, 123, 130, 139, 146, 153, 157, 166, 177, 182, 191, 202, 211, 220, 229, 236, 246, 251, 257, 266, 277, 283, 295, 303, 311, 321, 332}

func (i StandardMove) String() string {
	i -= 1
	if i < 0 || i >= StandardMove(len(_StandardMove_index)-1) {
		return fmt.Sprintf("StandardMove(%d)", i+1)
	}
	return _StandardMove_name[_StandardMove_index[i]:_StandardMove_index[i+1]]
}
