// Code generated by "stringer -type=StandardMove"; DO NOT EDIT

package move

import "fmt"

const _StandardMove_name = "AcidBiteBubbleBugBiteBulletPunchConfusionDragonBreathEmberFeintAttackFireFangFrostBreathFuryCutterIceShardKarateChopLickLowKickMetalClawMudShotMudSlapPeckPoisonJabPoisonStingPoundPsychoCutQuickAttackRazorLeafRockSmashRockThrowScratchShadowClawSparkSplashSteelWingSuckerPunchTackleThunderShockVineWhipWaterGunWingAttackZenHeadbutt"

var _StandardMove_index = [...]uint16{0, 4, 8, 14, 21, 32, 41, 53, 58, 69, 77, 88, 98, 106, 116, 120, 127, 136, 143, 150, 154, 163, 174, 179, 188, 199, 208, 217, 226, 233, 243, 248, 254, 263, 274, 280, 292, 300, 308, 318, 329}

func (i StandardMove) String() string {
	i -= 1
	if i < 0 || i >= StandardMove(len(_StandardMove_index)-1) {
		return fmt.Sprintf("StandardMove(%d)", i+1)
	}
	return _StandardMove_name[_StandardMove_index[i]:_StandardMove_index[i+1]]
}
