// Code generated by "stringer -type=Pokemon"; DO NOT EDIT

package de

import "fmt"

const _Pokemon_name = "BisasamBisaknospBisaflorGlumandaGlutexoGlurakSchiggySchillokTurtokRaupySafconSmettboHornliuKokunaBiborTaubsiTaubogaTaubossRattfratzRattikarlHabitakIbitakRettanArbokPikachuRaichuSandanSandamerNidoran_female_NidorinaNidoqueenNidoran_male_NidorinoNidokingPiepiPixiVulpixVulnonaPummeluffKnuddeluffZubatGolbatMyraplaDuflorGiflorParasParasekBluzukOmotDigdaDigdriMauziSnobilikatEntonEntoronMenkiRasaffFukanoArkaniQuapselQuaputziQuappoAbraKadabraSimsalaMacholloMaschockMachomeiKnofensaUltrigariaSarzeniaTentachaTentoxaKleinsteinGeorokGeowazPonitaGallopaFlegmonLahmusMagnetiloMagnetonPorentaDoduDodriJurobJugongSleimaSleimokMuschasAustosNebulakAlpolloGengarOnixTraumatoHypnoKrabbyKinglerVoltobalLektrobalOweiKokoweiTragossoKnoggaKickleeNockchanSchlurpSmogonSmogmogRihornRizerosChaneiraTangelaKangamaSeeperSeemonGoldiniGolkingSternduStarmiePantimosSichlorRossanaElektekMagmarPinsirTaurosKarpadorGaradosLaprasDittoEvoliAquanaBlitzaFlamaraPorygonAmonitasAmorosoKabutoKabutopsAerodactylRelaxoArktosZapdosLavadosDratiniDragonirDragoranMewtuMew"

var _Pokemon_index = [...]uint16{0, 7, 16, 24, 32, 39, 45, 52, 60, 66, 71, 77, 84, 91, 97, 102, 108, 115, 122, 131, 140, 147, 153, 159, 164, 171, 177, 183, 191, 206, 214, 223, 236, 244, 252, 257, 261, 267, 274, 283, 293, 298, 304, 311, 317, 323, 328, 335, 341, 345, 350, 356, 361, 371, 376, 383, 388, 394, 400, 406, 413, 421, 427, 431, 438, 445, 453, 461, 469, 477, 487, 495, 503, 510, 520, 526, 532, 538, 545, 552, 558, 567, 575, 582, 586, 591, 596, 602, 608, 615, 622, 628, 635, 642, 648, 652, 660, 665, 671, 678, 686, 695, 699, 706, 714, 720, 727, 735, 742, 748, 755, 761, 768, 776, 783, 790, 796, 802, 809, 816, 823, 830, 838, 845, 852, 859, 865, 871, 877, 885, 892, 898, 903, 908, 914, 920, 927, 934, 942, 949, 955, 963, 973, 979, 985, 991, 998, 1005, 1013, 1021, 1026, 1029}

func (i Pokemon) String() string {
	i -= 1
	if i < 0 || i >= Pokemon(len(_Pokemon_index)-1) {
		return fmt.Sprintf("Pokemon(%d)", i+1)
	}
	return _Pokemon_name[_Pokemon_index[i]:_Pokemon_index[i+1]]
}
