// Code generated by "stringer -type=Type"; DO NOT EDIT

package zhHK

import "fmt"

const _Type_name = "普通火水草電擊冰格鬥毒地上飛行超能力蟲岩石幽靈龍惡鋼妖精"

var _Type_index = [...]uint8{0, 6, 9, 12, 15, 21, 24, 30, 33, 39, 45, 54, 57, 63, 69, 72, 75, 78, 84}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
